front/application/forms/login_form.py
from flask_wtf import FlaskForm
from wtforms import SubmitField, StringField, PasswordField
from wtforms.validators import InputRequired


class LoginForm(FlaskForm):
    username = StringField(label="Username", validators=[InputRequired()])
    password = PasswordField(label="Password", validators=[InputRequired()])
    submit = SubmitField(label="Login")

front/application/forms/sign_up_form.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField
from wtforms.validators import Email, EqualTo, InputRequired, Length, Regexp


class SignUpForm(FlaskForm):
    email = StringField(label='Your Email',
                        validators=[InputRequired(), Email(message='Invalid email!')])
    new_username = StringField(
        label='New Username', validators=[InputRequired()])
    new_password = PasswordField(
        label='New Password',
        validators=[
            InputRequired(),
            Regexp(
                regex='.*[A-Z]+.*',
                message='Password must contain at least one uppercase letter!'),
            Regexp(
                regex='.*[a-z]+.*',
                message='Password must contain at least one lowercase letter!'),
            Regexp(
                regex='.*[0-9]+.*',
                message='Password must contain at least one number!'),
            Regexp(
                regex='.*[!@#$%^&*]+.*',
                message='Password must contain at least one special character [!@#$%^&*]!'),
            Length(
                min=8,
                message='Password must contain at least 8 characters!')
        ])
    confirm_password = PasswordField(
        label='Confirm Password',
        validators=[
            InputRequired(),
            EqualTo(
                fieldname='new_password', message='Passwords must match!')
        ])

front/application/controllers/auth.py
# Import Dependencies
import sqlalchemy

from flask import Blueprint, request, flash, redirect, url_for
from flask.templating import render_template
from flask_login import login_user
from flask_login.utils import login_required, logout_user
from werkzeug.security import check_password_hash

from .utils import *
from ..forms.sign_up_form import SignUpForm
from ..models.user import User


# Instantiate Blueprint
auth = Blueprint('auth', __name__)


# Login API
@auth.route('/auth/login', methods=['POST'])
def login():
    username = request.form.get('username')
    password = request.form.get('password')

    user = User.query.filter_by(username=username).first()

    if not (user and password and check_password_hash(user.password, password)):
        flash('Please check your login details and try again.', category='warning')
        return redirect(url_for('routes.login'))

    login_user(user=user, remember=True)
    return redirect(url_for('routes.home'))


# Sign up API
@auth.route('/auth/sign-up', methods=['POST'])
def sign_up():
    form = SignUpForm(request.form)
    if form.validate():
        try:
            email = request.form.get('email')
            new_username = request.form.get('new_username')
            new_password = request.form.get('new_password')
            new_user_id = add_new_user(email=email, username=new_username, password=new_password)
            new_user = get_user(new_user_id)
            login_user(user=new_user)
            return redirect(url_for('routes.home'))
        except sqlalchemy.exc.IntegrityError:
            flash('Email or Username has already been taken!', category='error')
            return redirect(url_for('routes.sign_up'))
    else:
        return render_template('sign-up.html', form=form, loginMode=False)


# Log out API
@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('routes.index'))

front/application/controllers/routes.py
# Import Dependencies
from dateutil import tz
from datetime import datetime

from flask import Blueprint, render_template, send_from_directory
from flask_login.utils import login_required, current_user

from .utils import *
from .. import IMAGE_STORAGE_DIRECTORY
from ..forms.login_form import LoginForm
from ..forms.sign_up_form import SignUpForm
from ..forms.delete_form import DeleteForm


# Instantiate Blueprint
routes = Blueprint("routes", __name__)


# Index page
@routes.route('/')
@routes.route('/about')
@routes.route('/index')
def index():
    return render_template('about.html')


# Home page (new prediction)
@routes.route('/home')
@login_required
def home():
    return render_template('home.html')


# Dashboard page
@routes.route('/dashboard')
@login_required
def dashboard():
    del_form = DeleteForm()
    all_predictions = get_all_predictions(userid=current_user.id)  # type: ignore
    graphJSON = chart(all_predictions=all_predictions)
    return render_template('dashboard.html', all_predictions=all_predictions, graphJSON=graphJSON, convert_to_local_time=convert_to_local_time, del_form=del_form)


def convert_to_local_time(dt: datetime):
    utc_zone = tz.tzutc()
    local_zone = tz.tzlocal()

    return dt.replace(tzinfo=utc_zone).astimezone(local_zone)


@routes.route('/image/<filename>')
def fetch_image(filename):
    return send_from_directory(directory=IMAGE_STORAGE_DIRECTORY[0], path=filename)


# Login page (existing users)
@routes.route('/login')
def login():
    form = LoginForm()
    return render_template('login.html', form=form, loginMode=True)


# Login page (new users)
@routes.route('/sign-up')
def sign_up():
    form = SignUpForm()
    return render_template('sign-up.html', form=form, loginMode=False)

front/application/templates/about.html
{% extends "layout.html" %}
{% block content %}
<div class="row pt-5 ml-5 pl-5">
    <div class="col"></div>
    <div class="col-9 pl-5 p-4 bg-dark about-box text-light">
        <h2 class="mb-5">Welcome :)</h2>
        <p>
            This application is designed to recognize 13 different kinds of sports balls. To get started, login at the top or sign up if you do not already have an account. Do note that the you might have to register again the next time.
        </p>
        <p>
            Users can switch between 3 modes of input:
        </p>
        <ul>
            <li>Drawing</li>
            <li>File Upload</li>
            <li>Webcam Capture</li>
        </ul>
        <p>
            The recognized types of balls are as follows:
        </p>
        <ul>
            <li>baseball</li>
            <li>basketball</li>
            <li>beachball</li>
            <li>billiard ball</li>
            <li>bowling ball</li>
            <li>cricket ball</li>
            <li>football</li>
            <li>golf ball</li>
            <li>soccer ball</li>
            <li>tennis ball</li>
            <li>volleyball</li>
            <li>water polo ball</li>
            <li>wiffle ball</li>
        </ul>
        <p>
            Users can review their past predictions through the dashboard. Predictions can be filtered by clicking or double-clicking the corresponding labels in the legend of the pie chart.
        </p>
        <p class="mt-3 mb-0">
            Project done by Ethan and Joshua
        </p>
    </div>
    <div class="col"></div>
</div>
{% endblock %}

front/application/templates/dashboard.html
{% extends "layout.html" %}
{% block content %}
<div class="container dark-form mt-3">
    <div class="row mt-3">
        <div class="col-12 col-md-3 col-lg-3">
            <ul class="home_menu">
                <li class="nav-item">
                    <a href="{{ url_for('routes.home') }}" class="nav-link">
                        New Prediction</a>
                </li>
                <li class="nav-item">
                    <a href="#" class="nav-link active">
                        Dashboard</a>
                </li>
            </ul>
        </div>
        <div class="col-12 col-sm">
            <div class="row">
                <div class="col-12">
                    {{ render_flashes() }}
                </div>
            </div>
            <div class="row mb-3">
                <div class="col-12 bg-white">
                    <div id="chart" class="chart w-100"></div>
                </div>
            </div>
            {% for pred in all_predictions %}
            {{ render_card(pred.id, url_for('routes.fetch_image', filename=pred.filepath), pred.ball_type.capitalize(), pred.probability, convert_to_local_time(pred.uploaded_on).strftime("%d %b %y %H:%M"), del_form=del_form) }}
            {% endfor %}
        </div>
        <div class="col-lg-1"></div>
    </div>
    <script async>
        let graphs = {{ graphJSON | safe }};
        Plotly.plot('chart', graphs, {});
    </script>
    <script src="{{ url_for('static', filename='js/plot.js') }}" async></script>
</div>
{% endblock %}

front/application/templates/home.html
{% extends "layout.html" %}
{% block content %}
<div class="container dark-form mt-3">
    <div class="row">
        <div class="col-12 col-md-3">
            <ul class="home_menu w-100">
                <li class="nav-item">
                    <a href="#" class="nav-link active">
                        New Prediction</a>
                </li>
                <li class="nav-item">
                    <a href="{{ url_for('routes.dashboard') }}" class="nav-link">
                        Dashboard</a>
                </li>
            </ul>
        </div>
        <div class="col-12 col-md">
            <div class="row">
                {{ render_flashes() }}
                <ul class="nav nav-pills white p-0" id="prediction-mode" role="tablist">
                    <li class="nav-item col-4" role="presentation">
                        <button class="nav-link active w-100" id="draw-mode" data-bs-toggle="tab"
                            data-bs-target="#draw-content" type="button" role="tab" aria-controls="draw-content"
                            aria-selected="true" onclick="webcam.stop()">DRAW</button>
                    </li>
                    <li class="nav-item col-4" role="presentation">
                        <button class="nav-link w-100" id="file-mode" data-bs-toggle="tab" data-bs-target="#file-content"
                            type="button" role="tab" aria-controls="file-content" aria-selected="false"
                            onclick="webcam.stop()">FILE</button>
                    </li>
                    <li class="nav-item col-4" role="presentation">
                        <button class="nav-link w-100" id="cam-mode" data-bs-toggle="tab" data-bs-target="#cam-content"
                            type="button" role="tab" aria-controls="cam-content" aria-selected="false"
                            onclick="webcam.start()">WEBCAM</button>
                    </li>
                </ul>
            </div>
            <div class="row m-3">
                <div class="col-12 p-0">
                    <h3 id="result" class="bg-transparent">Welcome :)</h3>
                </div>
            </div>
            <div class="row">
                <div class="tab-content text-white p-0">
                    <div class="tab-pane fade show active pt-3" id="draw-content" role="tabpanel"
                        aria-labelledby="draw-mode">
                        {% include "includes/drawing_input.html" %}
                    </div>
                    <div class="tab-pane fade" id="file-content" role="tabpanel" aria-labelledby="file-mode">
                        {% include "includes/file_input.html" %}
                    </div>
                    <div class="tab-pane fade" id="cam-content" role="tabpanel" aria-labelledby="cam-mode">
                        {% include "includes/cam_input.html" %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

front/application/templates/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Metadata -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Ball Recognizer</title>

    <!-- Icon -->
    <link rel="icon" type="image/png" href="{{ url_for('static', filename='img/favicon.png')}}" />

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <!-- Custom CSS Stylesheets -->
    <link href="{{ url_for('static', filename='css/styles.css')}}" rel="stylesheet" />
    <link href="{{ url_for('static', filename='css/dark-forms.css')}}" rel="stylesheet" />

    <!-- JQuery core JS -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"
        integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous" defer></script>

    <!-- Bootstrap core JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"
        defer></script>

    <!-- Webcam JS -->
    <script type="text/javascript" src="https://unpkg.com/webcam-easy/dist/webcam-easy.min.js" defer></script>

    <!-- JS -->
    <script src="{{ url_for('static', filename='js/drawing_input.js') }}" defer></script>
    <script src="{{ url_for('static', filename='js/file_input.js') }}" defer></script>
    <script src="{{ url_for('static', filename='js/cam_input.js') }}" defer></script>

    <script src='https://cdn.plot.ly/plotly-latest.min.js'></script>
</head>

<body>
    <!-- Import all macros -->
    {% from "includes/macros.html" import render_flashes, render_field, render_card %}

    <!-- Responsive navbar-->
    {% include "includes/nav.html" %}

    <!-- Switchable content -->
    {% block content %}
    {% endblock %}

    <!-- Footer-->
    {% include "includes/footer.html" %}
</body>

</html>

front/application/templates/login.html
{% extends "layout.html" %}
{% block content %}
<div class="row pt-5">
    <div class="col"></div>
    <div class="dark-form col-10 col-md-8 col-lg-6 col-xl-4">
        {{ render_flashes() }}
        <form name="loginForm" action="{{ url_for('auth.login') }}" method="post">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                {{ render_field(form.username) }}
                {{ render_field(form.password) }}
                <p>
                    {{ form.submit(class_='form-control bg-primary text-white') }}
                </p>
            </fieldset>
        </form>
        <a class="toggle-login-mode" href="{{ url_for('routes.sign_up') }}">Dont have an account? Sign Up Here</a>
    </div>
    <div class="col"></div>
</div>
{% endblock %}

front/application/templates/sign-up.html
{% extends "layout.html" %}
{% block content %}
<div class="row pt-5">
    <div class="col"></div>
    <div class="dark-form col-10 col-md-8 col-lg-6 col-xl-4">
        {{ render_flashes() }}
        <form name="signUpForm" action="{{ url_for('auth.sign_up') }}" method="post" class="sign_up">
            {{ form.hidden_tag() }}
            <fieldset class="form-group pb-3">
                {{ render_field(form.email, placeholder_='E.g. john_doe@abc.net') }}
                {{ render_field(form.new_username, placeholder_='E.g. John Doe') }}
                <p class="mb-1">
                    Password Requirements:
                </p>
                <ul class="small">
                    <li>Minimum 8 Characters</li>
                    <li>At least one lowercase letter [a-z]</li>
                    <li>At least one uppercase letter [A-Z]</li>
                    <li>At least one digit [0-9]</li>
                    <li>At least one special character [!@#$%^&*]</li>
                </ul>
                {{ render_field(form.new_password) }}
                {{ render_field(form.confirm_password) }}
                <button type="submit" class="btn btn-success" disabled>Submit</button>
                <button type="reset" class="btn btn-warning">Cancel</button>
            </fieldset>
        </form>
        <a class="toggle-login-mode" href="{{ url_for('routes.login') }}">Have an account? Login Here</a>
    </div>
    <div class="col"></div>
</div>
{% endblock %}